# Generated by Django 5.2 on 2025-04-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_family_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familygroupmembership',
            name='family_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family_tree.familygroup'),
        ),
        migrations.AddField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familygroupmembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='family_tree.person'),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='members',
            field=models.ManyToManyField(related_name='family_groups', through='family_tree.FamilyGroupMembership', to='family_tree.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person1', to='family_tree.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='person2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_person2', to='family_tree.person'),
        ),
        migrations.AlterUniqueTogether(
            name='familygroupmembership',
            unique_together={('person', 'family_group')},
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('person1', 'person2', 'relationship_type')},
        ),
    ]
