# Generated by Django 5.2 on 2025-04-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10, verbose_name='status')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='publish date')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='event date')),
                ('event_location', models.CharField(blank=True, max_length=255, verbose_name='event location')),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
            ],
            options={
                'verbose_name': 'story collection',
                'verbose_name_plural': 'story collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryInCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'story in collection',
                'verbose_name_plural': 'stories in collections',
                'ordering': ['order', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('PERSON', 'Person'), ('MEDIA', 'Media Item'), ('LOCATION', 'Location'), ('EVENT', 'Event'), ('URL', 'External URL'), ('OTHER', 'Other')], max_length=10, verbose_name='reference type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='position')),
            ],
            options={
                'verbose_name': 'story reference',
                'verbose_name_plural': 'story references',
                'ordering': ['story', 'position'],
            },
        ),
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'story tag',
                'verbose_name_plural': 'story tags',
            },
        ),
    ]
