# Generated by Django 5.2 on 2025-04-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0002_initial'),
        ('media', '0002_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='stories.comment'),
        ),
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_stories', to='media.mediaitem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storycollection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_story_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storyincollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.storycollection'),
        ),
        migrations.AddField(
            model_name='storyincollection',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_entries', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storyreference',
            name='media_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referenced_in_stories', to='media.mediaitem'),
        ),
        migrations.AddField(
            model_name='storyreference',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentioned_in_stories', to='family_tree.person'),
        ),
        migrations.AddField(
            model_name='storyreference',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storytag',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='stories.story'),
        ),
        migrations.AddField(
            model_name='storytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_stories', to='media.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='storyincollection',
            unique_together={('story', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='storytag',
            unique_together={('story', 'tag')},
        ),
    ]
