# Generated by Django 5.2 on 2025-04-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0002_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediainalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='media.album'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='media_items', to='media.mediacategory'),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediainalbum',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_entries', to='media.mediaitem'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='media.mediaitem'),
        ),
        migrations.AddField(
            model_name='mediatag',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_media_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediatag',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='media.mediaitem'),
        ),
        migrations.AddField(
            model_name='personinmedia',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_person_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personinmedia',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_people', to='media.mediaitem'),
        ),
        migrations.AddField(
            model_name='personinmedia',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_appearances', to='family_tree.person'),
        ),
        migrations.AddField(
            model_name='mediatag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_tags', to='media.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='mediainalbum',
            unique_together={('media_item', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='personinmedia',
            unique_together={('media_item', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='mediatag',
            unique_together={('media_item', 'tag')},
        ),
    ]
