# Generated by Django 5.2 on 2025-04-11 02:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_clicked_activation_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
