# Generated by Django 5.2 on 2025-04-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_access_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='provider access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_refresh_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='provider refresh token'),
        ),
        migrations.AddField(
            model_name='user',
            name='provider_token_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='provider token expiry'),
        ),
    ]
